apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app
  POSTGRES_DB: order
  DATABASE_URL: postgres://app:app@postgres:5432/order?sslmode=disable
